"""initial

Revision ID: a0a5de490e2f
Revises:
Create Date: 2025-09-22 02:19:26.366984

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0a5de490e2f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("make", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("vin", sa.String(length=17), nullable=False),
        sa.Column("engine", sa.String(length=50), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum("GASOLINE", "DIESEL", "ELECTRIC", "HYBRID", name="vehiclefueltype"),
            nullable=False,
        ),
        sa.Column(
            "transmission",
            sa.Enum("MANUAL", "AUTOMATIC", name="vehicletransmission"),
            nullable=False,
        ),
        sa.Column(
            "color",
            sa.Enum(
                "BLACK",
                "WHITE",
                "SILVER",
                "GRAY",
                "BLUE",
                "RED",
                "OTHER",
                name="vehiclecolor",
            ),
            nullable=False,
        ),
        sa.Column("color_detail", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("doors", sa.Integer(), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vin"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicles")
    # ### end Alembic commands ###
